export const perfil = {
    nombre: 'Joaquin',
    apellido: 'Quiroga',
    email: 'joaquinquiroga22@gmail.com',
}

export const productos = [
    {
        id: 1,
        nombre: 'Computadora 1',
        descripcion: 'Descripción de computadora 1',
        marca: 'Dell',
        categoria: 'computadora',
        precio: 2500,
        descuento: 0,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 2,
        nombre: 'Celular 1',
        descripcion: 'Descripción de celular 1',
        marca: 'Motorola',
        categoria: 'celular',
        precio: 1000,
        descuento: 10,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 3,
        nombre: 'Celular 2',
        descripcion: 'Descripción de celular 2',
        marca: 'Iphone',
        categoria: 'celular',
        precio: 2000,
        descuento: 0,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 4,
        nombre: 'Computadora 2',
        descripcion: 'Descripción de computadora 2',
        marca: 'Lenovo',
        categoria: 'computadora',
        precio: 2000,
        descuento: 30,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 5,
        nombre: 'Computadora 3',
        descripcion: 'Descripción de computadora 3',
        marca: 'Dell',
        categoria: 'computadora',
        precio: 1900,
        descuento: 25,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 6,
        nombre: 'Computadora 6',
        descripcion: 'Descripción de computadora 4',
        marca: 'Dell',
        categoria: 'computadora',
        precio: 2500,
        descuento: 0,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 7,
        nombre: 'Celular 7',
        descripcion: 'Descripción de celular 7',
        marca: 'Motorola',
        categoria: 'celular',
        precio: 1000,
        descuento: 10,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 8,
        nombre: 'Celular 8',
        descripcion: 'Descripción de celular 8',
        marca: 'Iphone',
        categoria: 'celular',
        precio: 2000,
        descuento: 0,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 9,
        nombre: 'Computadora 9',
        descripcion: 'Descripción de computadora 9',
        marca: 'Lenovo',
        categoria: 'computadora',
        precio: 2000,
        descuento: 30,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 10,
        nombre: 'Computadora 10',
        descripcion: 'Descripción de computadora 10',
        marca: 'Dell',
        categoria: 'computadora',
        precio: 1900,
        descuento: 25,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 11,
        nombre: 'Computadora 11',
        descripcion: 'Descripción de computadora 11',
        marca: 'Dell',
        categoria: 'computadora',
        precio: 2500,
        descuento: 0,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 12,
        nombre: 'Celular 12',
        descripcion: 'Descripción de celular 12',
        marca: 'Motorola',
        categoria: 'celular',
        precio: 1000,
        descuento: 10,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 13,
        nombre: 'Celular 13',
        descripcion: 'Descripción de celular 13',
        marca: 'Iphone',
        categoria: 'celular',
        precio: 2000,
        descuento: 0,
        favorito: true,
        cantidad_a_comprar: 0,
    },
    {
        id: 14,
        nombre: 'Computadora 14',
        descripcion: 'Descripción de computadora 14',
        marca: 'Lenovo',
        categoria: 'computadora',
        precio: 2000,
        descuento: 30,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 15,
        nombre: 'Computadora 15',
        descripcion: 'Descripción de computadora 15',
        marca: 'Dell',
        categoria: 'computadora',
        precio: 1900,
        descuento: 25,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 16,
        nombre: 'Computadora 16',
        descripcion: 'Descripción de computadora 16',
        marca: 'Dell',
        categoria: 'computadora',
        precio: 2500,
        descuento: 0,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 17,
        nombre: 'Celular 17',
        descripcion: 'Descripción de celular 17',
        marca: 'Motorola',
        categoria: 'celular',
        precio: 1000,
        descuento: 10,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 18,
        nombre: 'Celular 18',
        descripcion: 'Descripción de celular 18',
        marca: 'Iphone',
        categoria: 'celular',
        precio: 2000,
        descuento: 0,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 19,
        nombre: 'Computadora 19',
        descripcion: 'Descripción de computadora 19',
        marca: 'Lenovo',
        categoria: 'computadora',
        precio: 2000,
        descuento: 30,
        favorito: false,
        cantidad_a_comprar: 0,
    },
    {
        id: 20,
        nombre: 'Computadora 20',
        descripcion: 'Descripción de computadora 20',
        marca: 'Dell',
        categoria: 'computadora',
        precio: 1900,
        descuento: 25,
        favorito: false,
        cantidad_a_comprar: 0,
    },
]